# Generated by Django 5.1 on 2024-08-26 05:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_description', models.CharField(max_length=200)),
                ('brand_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand_slogan', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_category_name', models.CharField(max_length=200)),
                ('product_category_description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_image_name', models.CharField(max_length=200)),
                ('product_image_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='product_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('product_status_name', models.CharField(max_length=200)),
                ('product_status_description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='suppliers_levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('supplier_level_name', models.CharField(max_length=200)),
                ('supplier_level_description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='suppliers_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('supplier_status_name', models.CharField(max_length=200)),
                ('supplier_status_description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_description', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=200)),
                ('supplier_brand', models.ManyToManyField(to='vanguard.brands')),
                ('supplier_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vanguard.suppliers_levels')),
                ('supplier_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vanguard.suppliers_status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='supplier_warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('supplier_warehouse_name', models.CharField(max_length=200)),
                ('supplier_warehouse_description', models.CharField(max_length=200)),
                ('supplier_warehouse_adress', models.CharField(max_length=200)),
                ('supplier_warehouse_state', models.CharField(max_length=200)),
                ('supplier_warehouse_city', models.CharField(max_length=200)),
                ('supplier_warehouse_supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='vanguard.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('part_number', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('google_title', models.CharField(max_length=200)),
                ('specs', models.TextField()),
                ('sku', models.CharField(max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.CharField(max_length=200)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('deep', models.FloatField()),
                ('category', models.ManyToManyField(to='vanguard.product_categories')),
                ('product_images', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vanguard.product_images')),
                ('product_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vanguard.product_status')),
                ('supplier', models.ManyToManyField(to='vanguard.suppliers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
