# Generated by Django 5.1 on 2024-08-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vanguard', '0003_alter_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio compra'),
        ),
    ]
