# Generated by Django 5.1 on 2024-08-26 05:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('halberd', '0001_initial'),
        ('vanguard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_method_name', models.CharField(max_length=200)),
                ('payment_method_description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sale_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sale_status_name', models.CharField(max_length=200)),
                ('sale_status_description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('total_amount', models.FloatField(max_length=200)),
                ('billing_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='halberd.user_bill_adress')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='silkroad.payment_method')),
                ('shipment_adress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='halberd.user_shipment_adress')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='silkroad.sale_status')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sale_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sale_details_product_price', models.FloatField()),
                ('sale_details_product_amount', models.IntegerField()),
                ('sale_details_producto_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vanguard.products')),
                ('sale_details_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='silkroad.sale_status')),
                ('sale_details_sale_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='silkroad.sales')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
