# Generated by Django 5.1 on 2024-08-26 05:47

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_level_name', models.CharField(max_length=200)),
                ('user_level_description', models.TextField(blank=True)),
                ('user_level_assigned_number', models.CharField(max_length=2)),
                ('user_level_assigned_letter', models.CharField(max_length=2)),
                ('user_level_short_name', models.CharField(max_length=50)),
                ('user_level_code_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_status_name', models.CharField(max_length=200)),
                ('user_status_description', models.TextField(blank=True)),
                ('user_status_assigned_letter', models.CharField(max_length=2)),
                ('user_status_short_name', models.CharField(max_length=50)),
                ('user_status_code_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_type_name', models.CharField(max_length=200)),
                ('user_type_description', models.TextField(blank=True)),
                ('user_type_short_name', models.CharField(max_length=50)),
                ('user_type_code_name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('names', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('lastname2', models.CharField(max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Mexico', max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('credit', models.BooleanField(default=False)),
                ('credit_limit', models.FloatField(default=0)),
                ('debt', models.FloatField(default=0)),
                ('validation_code', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_access', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('user_level', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='halberd.user_level')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='halberd.user_status')),
                ('user_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='halberd.user_type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='assigned_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('assigned_user_assigned_salesman_email', models.EmailField(max_length=200)),
                ('assigned_user_unassigment_date', models.DateTimeField(blank=True, max_length=50)),
                ('assigned_user_unassign_reason', models.CharField(blank=True, max_length=200)),
                ('assigned_user_status', models.BooleanField(default=False, max_length=200)),
                ('assigned_user_comments', models.TextField(blank=True)),
                ('assigned_user_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_bill_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_bill_adress_rfc', models.CharField(blank=True, max_length=20)),
                ('user_bill_adress_street', models.CharField(blank=True, max_length=50)),
                ('user_bill_adress_int_number', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_ext_number', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_colony', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_postal_code', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_city', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_municipio', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_state', models.CharField(blank=True, max_length=200)),
                ('user_bill_adress_email', models.EmailField(blank=True, max_length=200)),
                ('user_bill_adress_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user_shipment_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user_shipment_adress_name', models.CharField(blank=True, max_length=200)),
                ('user_shipment_adress_company_name', models.CharField(blank=True, max_length=200)),
                ('user_shipment_adress_street', models.CharField(blank=True, max_length=50)),
                ('user_shipment_adress_int_number', models.CharField(blank=True, max_length=7)),
                ('user_shipment_adress_ext_number', models.CharField(blank=True, max_length=7)),
                ('user_shipment_adress_colony', models.CharField(blank=True, max_length=50)),
                ('user_shipment_adress_postal_code', models.CharField(blank=True, max_length=10)),
                ('user_shipment_adress_city', models.CharField(blank=True, max_length=100)),
                ('user_shipment_adress_municipio', models.CharField(blank=True, max_length=100)),
                ('user_shipment_adress_state', models.CharField(blank=True, max_length=100)),
                ('user_shipment_adress_phone', models.CharField(blank=True, max_length=100)),
                ('user_shipment_adress_email', models.EmailField(blank=True, max_length=200)),
                ('user_shipment_adress_references', models.CharField(blank=True, max_length=100)),
                ('user_shipment_adress_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
