# Generated by Django 5.1 on 2024-08-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halberd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='validation_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
